/**
 * One-time generator: walks nyc-neighborhoods.json (NTA polygons) + NTA_ALIASES
 * to produce a colloquial-neighborhood → borough mapping, then prints it as a
 * TypeScript record so it can be pasted into lib/borough-lookup.ts.
 *
 * Custom zones (nyc-custom-zones.ts) split compound NTAs into sub-neighborhoods
 * that the polygon lookup never sees — their borough assignments are appended
 * manually below since we know which NTA (and therefore borough) they come from.
 */
import nycNeighborhoods from "../lib/nyc-neighborhoods.json";
import { NTA_ALIASES } from "../lib/nyc-nta-aliases";

interface NtaFeature {
  type: "Feature";
  properties: { name: string; borough: string };
}

const lookup: Record<string, string> = {};

// NTA polygon features → apply alias → record colloquial→borough
for (const feature of (nycNeighborhoods as { features: NtaFeature[] }).features) {
  const { name, borough } = feature.properties;
  const colloquial = NTA_ALIASES[name] ?? name;
  // Multiple NTAs may alias to the same colloquial name (all same borough — safe to overwrite)
  lookup[colloquial] = borough;
}

// Custom zone names not reachable via NTA alias lookup.
// These are sub-neighborhoods carved out of compound NTAs; the borough is known
// from the parent NTA.
const CUSTOM_ZONE_BOROUGHS: Record<string, string> = {
  // Manhattan — SoHo-Little Italy-Hudson Square split
  "Hudson Square":     "Manhattan",
  "SoHo":              "Manhattan",
  "Nolita":            "Manhattan",
  "Little Italy":      "Manhattan",
  // Manhattan — Midtown-Times Square split
  "Hell's Kitchen":    "Manhattan",
  // Manhattan — Midtown South-Flatiron-Union Square split
  "Union Square":      "Manhattan",
  "NoMad":             "Manhattan",
  // Manhattan — Financial District-Battery Park City split
  "Battery Park City": "Manhattan",
  // Manhattan — Tribeca-Civic Center split
  "Civic Center":      "Manhattan",
  // Brooklyn — Downtown Brooklyn-DUMBO-Boerum Hill split
  "DUMBO":             "Brooklyn",
  "Boerum Hill":       "Brooklyn",
  "Downtown Brooklyn": "Brooklyn",
  // Brooklyn — Carroll Gardens-Cobble Hill-Gowanus-Red Hook split
  "Cobble Hill":       "Brooklyn",
  "Gowanus":           "Brooklyn",
  "Red Hook":          "Brooklyn",
};

for (const [name, borough] of Object.entries(CUSTOM_ZONE_BOROUGHS)) {
  lookup[name] = borough;
}

// Sort keys alphabetically and print as a TS record literal
const sorted = Object.fromEntries(
  Object.entries(lookup).sort(([a], [b]) => a.localeCompare(b))
);

console.log("// Auto-generated by scripts/generate-borough-lookup.ts — do not hand-edit.");
console.log("// Re-run the script if nyc-neighborhoods.json or nyc-nta-aliases.ts change.");
console.log("");
console.log("export const BOROUGH_LOOKUP: Record<string, string> = {");
for (const [name, borough] of Object.entries(sorted)) {
  const escaped = name.replace(/'/g, "\\'");
  console.log(`  '${escaped}': '${borough}',`);
}
console.log("};");
console.log("");
console.log(`// ${Object.keys(sorted).length} neighborhoods mapped`);
